// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbeznheocdizsmsizszo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_Xn2NVoJOf7w_Tk1J1l48UA_ykZ-Gy9S";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);