// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utjvkudemriymlmfvqjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0anZrdWRlbXJpeW1sbWZ2cWp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzkwNDcsImV4cCI6MjA2MTE1NTA0N30.OLSr05PzxNrsMjWKhp0HHMPZ6opRJ4JP5QPG64R3C00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);